title: Sécurité
icon: 'mdi:cctv'
cards:

  - type: horizontal-stack
    cards:
      - type: 'custom:owntrack-card'
        entities: 
          - device_tracker.oneplus_a6010
          - sensor.oneplus_a6010_niveau_de_batterie
        image: '/local/photo/dim.png'
        
      - type: 'custom:owntrack-card'
        entities: 
          - device_tracker.patoo
          - sensor.patoo_niveau_de_batterie
        image: '/local/photo/patoo.png'
    
  - type: map
    aspect_ratio: 1.78
    default_zoom: 10
    entities:
      - device_tracker.oneplus_a6010
      - device_tracker.patoo
      - zone.home
      - zone.ovh
      - zone.ecole
      
  - type: picture-glance
    title: Garage
    entities: 
      - switch.dafang_ir_filter
      - switch.dafang_ir_led
      - switch.dafang_night_mode
      - binary_sensor.dafang_motion_sensor
    camera_image: camera.garage_camera
