homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include_dir_merge_named customize/
  internal_url: !secret internal_url
  external_url: !secret external_url
  packages: !include_dir_named packages/

default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Enables the frontend
frontend:
  javascript_version: auto

lovelace:
  mode: yaml

panel_iframe: !include lovelace/panel.yaml

discovery:
local_ip:
stream:
conversation:
upnp:
tplink:
livebox: !include components/livebox.yaml
influxdb: !include components/influxdb.yaml
rflink: !include components/rflink.yaml
octoprint: !include components/octoprint.yaml
spotify: !include components/spotify.yaml
sabnzbd: !include components/sabnzbd.yaml
speedtestdotnet: !include components/speedtestdotnet.yaml
calendar: !include components/calendar.yaml
hue: !include components/hue.yaml
mqtt: !include components/mqtt.yaml
tts: !include components/tts.yaml
media_player: !include components/mediaplayer.yaml
camera: !include components/camera.yaml
weather: !include components/weather.yaml
plant: !include components/plant.yaml
device_tracker: !include components/device_tracker.yaml
logger: !include components/logger.yaml

cover: !include_dir_merge_list cover/
light: !include_dir_merge_list light/
switch: !include_dir_merge_list switch/
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/

automation: !include_dir_merge_list automation/
script: !include_dir_merge_list script/
group: !include_dir_merge_named group/
zone: !include zone.yaml
scene: !include_dir_merge_list scene/
