homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 70
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Enables the frontend
frontend:
  javascript_version: auto

lovelace:
  mode: yaml  

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_url

local_ip:

stream:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:


# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'fr'


upnp:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

    
rflink:
  port: 6000
  host: !secret rflink
  
#rflink2:
#  port: /dev/ttyACM2

tplink:

octoprint:
  host: !secret orb
  port: 5000
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

logger:
  default: error
#  logs:
#    rflink: debug
#    homeassistant.components.rflink: debug

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: !secret orb
  name: sabnzbd
  port: 8080
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size
  
speedtestdotnet:
  scan_interval:
    minutes: 180
  monitored_conditions:
    - ping
    - download
    - upload

calendar:
  - platform: caldav
    url: !secret caldav_url
    username: !secret caldav_username
    password: !secret caldav_password


#glances:
#  port: 61209
#  name: 127.0.0.1
#  ssl: true
#  verify_ssl: false

#linky:
#  username: !secret linky_username
#  password: !secret linky_password

cover:
  platform: opengarage
  covers:
    garage:
      host: !secret opengarage
      device_key: !secret opengarage_device_key
      name: Garage Door


media_player: !include mediaplayer.yaml
light: !include light.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
camera: !include camera.yaml
weather: !include weather.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zone.yaml
group: !include groups.yaml
plant: !include plant.yaml