- platform: rflink
  automatic_add: true
  devices:
    fineoffset_003d_bat:
      name: Batterie chambre Noah
      sensor_type: battery
    fineoffset_003d_temp:
      name: Temperature chambre Noah
      sensor_type: temperature
    fineoffset_003d_hum:
      name: Humidité chambre Noah
      sensor_type: humidity
    fineoffset_005b_bat:
      name: Batterie bureau Dimitri
      sensor_type: battery
    fineoffset_005b_temp:
      name: Temperature bureau Dimitri
      sensor_type: temperature
    fineoffset_005b_hum:
      name: Humidité bureau Dimitri
      sensor_type: humidity
    fineoffset_001d_bat:
      name: batterie chambre Parentale
      sensor_type: battery
    fineoffset_001d_temp:
      name: Temperature chambre Parentale
      sensor_type: temperature
    fineoffset_001d_hum:
      name: Humidité chambre Parentale
      sensor_type: humidity
    inovalley_0b01_bat:
      name: batterie Salon
      sensor_type: battery
    inovalley_0b01_temp:
      name: Temperature Salon
      sensor_type: temperature
    inovalley_0b01_hum:
      name: Humidité Salon
      sensor_type: humidity
    wh3_4b00_temp:
      name: Temperature Salle de bain
      sensor_type: temperature
    wh3_4b00_hum:
      name: Humidité Salle de bain
      sensor_type: humidity
    wh3_4490_temp:
      name: Temperature alcôve
      sensor_type: temperature
    wh3_4490_hum:
      name: Humidité alcôve
      sensor_type: humidity
    wh3_4c90_temp:
      name: Temperature chambre Soline
      sensor_type: temperature
    wh3_4c90_hum:
      name: Humidité Chambre Soline
      sensor_type: humidity

- platform: template
  sensors:
    garage_status:
      friendly_name: 'Garage Status'
      icon_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.attributes["door_state"] == "open" %}
            mdi:garage-open
          {% elif states.cover.garage_door.attributes["door_state"] == "closed" %}
            mdi:garage-alert
          {% elif states.cover.garage_door.attributes["door_state"] == "opening" %}
            mdi:garage-alert
          {% elif states.cover.garage_door.attributes["door_state"] == "closing" %}
            mdi:garage
          {% else %}
             mdi:garage
          {% endif %}
          {% else %}
           mdi:garage
          {% endif %}'
      value_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
