views:
  - !include lovelace/ui-floorplan.yaml
  - !include lovelace/ui-home.yaml
  - !include lovelace/ui-weather.yaml
  - !include lovelace/ui-media.yaml
  - !include lovelace/ui-security.yaml
  - !include lovelace/ui-network.yaml
