

resources:
  - url: /local/custom_ui/linky-card.js?v=0
    type: js
  - url: /local/custom_ui/ext-weblink.js?v=0
    type: js
  - url: /local/custom_ui/owntrack-card.js?v=0
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module


views:
  - !include lovelace/ui-floorplan.yaml
  - !include lovelace/ui-home.yaml
  - !include lovelace/ui-weather.yaml
  - !include lovelace/ui-media.yaml
  - !include lovelace/ui-security.yaml
  - !include lovelace/ui-network.yaml

